{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ai.cowsdk",
    "module": "by",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.otaliastudios",
          "module": "cameraview",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "by-1.0.5.aar",
          "url": "by-1.0.5.aar",
          "size": 22423987,
          "sha512": "f989c046629875df8363cd4aa27b8d22b3508c079574bc18b195e33f7fa12e98209f5766b57a2bf510fcf4b8c8f75b4288bcb97683ff3dd4185838d087a623cf",
          "sha256": "03aa9f26ad53a4c974047d12c7fb9db1f3d685e1cb6778acd216335ce57610d4",
          "sha1": "27a48c47d060f93e5f45b455612651fafe547c32",
          "md5": "86fe89a8d689b755def4e0bae2d8ecab"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.quickbirdstudios",
          "module": "opencv",
          "version": {
            "requires": "4.1.0"
          }
        },
        {
          "group": "com.github.Blincheng",
          "module": "EToast2",
          "version": {
            "requires": "v2.1.0"
          }
        },
        {
          "group": "top.zibin",
          "module": "Luban-turbo",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.pytorch",
          "module": "pytorch_android",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.pytorch",
          "module": "pytorch_android_torchvision",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "io.github.silvaren",
          "module": "easyrs",
          "version": {
            "requires": "0.5.3"
          }
        },
        {
          "group": "com.yanzhenjie.permission",
          "module": "support",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.zyao89",
          "module": "zloading",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.ar.sceneform",
          "module": "core",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.blankj",
          "module": "utilcode",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.github.zhaokaiqiang.klog",
          "module": "library",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.lzy.net",
          "module": "okgo",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "com.github.dfqin",
          "module": "grantor",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.github.CymChad",
          "module": "BaseRecyclerViewAdapterHelper",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.11.0"
          }
        },
        {
          "group": "com.github.lany192",
          "module": "KVUtils",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "com.tencent",
          "module": "mmkv-static",
          "version": {
            "requires": "1.2.9"
          }
        },
        {
          "group": "com.squareup.tape2",
          "module": "tape",
          "version": {
            "requires": "2.0.0-beta1"
          }
        },
        {
          "group": "org.eclipse.paho",
          "module": "org.eclipse.paho.client.mqttv3",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "org.eclipse.paho",
          "module": "org.eclipse.paho.android.service",
          "version": {
            "requires": "+"
          }
        },
        {
          "group": "com.github.ankushyerawar",
          "module": "FloatingSnackBar",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.bigkoo",
          "module": "alertview",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "com.ethanhua",
          "module": "skeleton",
          "version": {
            "requires": "1.1.2"
          }
        },
        {
          "group": "io.supercharge",
          "module": "shimmerlayout",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.github.tamsiree.RxTool",
          "module": "RxKit",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.contrarywind",
          "module": "Android-PickerView",
          "version": {
            "requires": "4.1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.amap.api",
          "module": "search",
          "version": {
            "requires": "8.1.0"
          }
        },
        {
          "group": "me.jessyan",
          "module": "autosize",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.qiniu",
          "module": "qiniu-android-sdk",
          "version": {
            "requires": "8.2.+"
          },
          "excludes": [
            {
              "group": "com.squareup.okhttp3",
              "module": "okhttp"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.otaliastudios",
          "module": "cameraview",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.1.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "by-1.0.5.aar",
          "url": "by-1.0.5.aar",
          "size": 22423987,
          "sha512": "f989c046629875df8363cd4aa27b8d22b3508c079574bc18b195e33f7fa12e98209f5766b57a2bf510fcf4b8c8f75b4288bcb97683ff3dd4185838d087a623cf",
          "sha256": "03aa9f26ad53a4c974047d12c7fb9db1f3d685e1cb6778acd216335ce57610d4",
          "sha1": "27a48c47d060f93e5f45b455612651fafe547c32",
          "md5": "86fe89a8d689b755def4e0bae2d8ecab"
        }
      ]
    }
  ]
}
